language: python

python:
  - "3.6"
env:
  - SECRET_KEY="5^&$#%"
install:
  - pip install -r requirements.txt
  - pip install coverage

script:
  - nosetests --with-coverage --cover-package=app

after_script:
  - coveralls    
